name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Check theme directory and download if needed
        run: |
          echo "Theme directory contents:"
          ls -la themes/
          if [ ! -d "themes/hugo-profile" ]; then
            echo "Theme not found, downloading..."
            mkdir -p themes
            git clone https://github.com/gurusabarish/hugo-profile.git themes/hugo-profile
          fi
          echo "Hugo profile theme directory contents:"
          ls -la themes/hugo-profile/

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Node.js dependencies
        run: |
          npm ci || npm install
          cd themes/hugo-profile
          npm install
          cd ../..

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: List Hugo version and environment
        run: |
          hugo version
          hugo env

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --minify --gc --themesDir=themes --baseURL "https://arraiz.github.io/albavilardell/"
          
      - name: List output directory
        run: |
          echo "Listing contents of public directory"
          ls -la public
          
      - name: Check CSS files
        run: |
          echo "Checking CSS files"
          find public -name "*.css" | sort
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
